// A run's name for people (wake/v1's `wake:started`): two words, the same
// on the app, in the herdr tab, in `wakectl status` and in the log, so a
// person can say "amber-heron" instead of reading out a session id. Made
// from Wake's own id for the run, so it is known before the tool starts.

const FIRST = [
  "amber",
  "brave",
  "brisk",
  "calm",
  "clever",
  "coral",
  "crisp",
  "dapper",
  "eager",
  "early",
  "fair",
  "fleet",
  "gentle",
  "golden",
  "happy",
  "hazel",
  "honest",
  "jolly",
  "keen",
  "kind",
  "lively",
  "lucky",
  "mellow",
  "merry",
  "misty",
  "modest",
  "neat",
  "nimble",
  "noble",
  "olive",
  "patient",
  "plucky",
  "polite",
  "proud",
  "quick",
  "quiet",
  "rapid",
  "ready",
  "rosy",
  "rustic",
  "sandy",
  "silver",
  "sleek",
  "sly",
  "snowy",
  "sober",
  "spry",
  "steady",
  "stout",
  "sunny",
  "swift",
  "tidy",
  "true",
  "tender",
  "valiant",
  "velvet",
  "vivid",
  "warm",
  "wily",
  "windy",
  "wise",
  "witty",
  "young",
  "zesty",
];

const SECOND = [
  "badger",
  "beaver",
  "bison",
  "crane",
  "cricket",
  "dolphin",
  "falcon",
  "ferret",
  "finch",
  "fox",
  "gecko",
  "gopher",
  "grouse",
  "hare",
  "hawk",
  "heron",
  "ibex",
  "jackal",
  "jay",
  "kestrel",
  "kiwi",
  "koala",
  "lark",
  "lemur",
  "lynx",
  "magpie",
  "marten",
  "mink",
  "moose",
  "newt",
  "ocelot",
  "otter",
  "owl",
  "panda",
  "pelican",
  "petrel",
  "pika",
  "plover",
  "puffin",
  "quail",
  "raven",
  "robin",
  "salmon",
  "seal",
  "shrike",
  "sparrow",
  "stoat",
  "swan",
  "tapir",
  "tern",
  "thrush",
  "toucan",
  "trout",
  "turtle",
  "vole",
  "walrus",
  "weasel",
  "whale",
  "wombat",
  "wren",
  "yak",
  "zebra",
  "osprey",
  "bobcat",
];

/** FNV-1a: small, stable, and enough to spread ids over 4,096 names. */
function hash(text: string): number {
  let h = 0x811c9dc5;
  for (let i = 0; i < text.length; i++) {
    h ^= text.charCodeAt(i);
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  return h;
}

export function runName(id: string): string {
  const h = hash(id);
  return `${FIRST[h % FIRST.length]}-${SECOND[(h >>> 8) % SECOND.length]}`;
}
